### ISSUE TITLE
MCUBoot Serial Recovery reports "command not supported" after Image upload

### ISSUE THREAD

**Issue by butok** [thedjnK/AuTerm#33] opened 2024-11-21 14:43 UTC
AuTerm application reports "command not supported" after Upload via UART, for MCUBoot Serial Recovery.

Steps:
- Build & flash bootloader/mcuboot/boot/zephyr  with enabled Serial Recovery.
- Connect EVB board to Serial port
- Start latest AuTerm v0.34c
- Connect via UART on the MCUmgr tab.
- Go to the Upload tab and choose a binary for upload.
- Press [Go] button.
- **Image upload is successful**
- BUT When the upload progress is reaching 100%, the AuTem prints "command not supported":

![image](https://github.com/user-attachments/assets/8b74eceb-e823-41e7-bb3d-50477838b031)

**Comment by thedjnK** [comment] 2024-11-21 14:47
This is because `test` is ticked, that will mark the image for test after it has been updated, but serial recovery in MCUboot (by default) does not have support for the image state set command, see https://github.com/mcu-tools/mcuboot/blob/main/boot/zephyr/Kconfig.serial_recovery#L199 as it will directly to the primary slot, not the secondary slot which means the image is confirmed already

**Comment by thedjnK** [comment] 2024-11-21 15:18
Yes, test/confirm are setting the image state (only difference is confirm has the confirm option but they are the same command), you can enable the Kconfig for MCUboot to use them but there's no point because it loads to the primary slot and the primary slot is always confirmed when you do a firmware update directly there (only reason to use it would be if you enable the Kconfig for supporting the slot number as then you can upload to the secondary slot), so for MCUboot you can leave it at `No action`

**Comment by thedjnK** [comment] 2024-11-21 15:31
I'll add some more debug for that as the issue is not addressed after all. How long does it take to upload that file to your device, less than 1 second?

**Comment by butok** [comment] 2024-11-21 15:32
> I'll add some more debug for that as the issue is not addressed after all. How long does it take to upload that file to your device, less than 1 second?

<1 second

**Comment by butok** [comment] 2024-11-21 15:35
BTW: Is it possible to add more information "what exact command" is not supported to the "command is not supported" message?

**Comment by thedjnK** [comment] 2024-11-22 09:13
> > I'll add some more debug for that as the issue is not addressed after all. How long does it take to upload that file to your device, less than 1 second?
> 
> <1 second

You have the fastest device/upload using MCUmgr I've ever seen

Give this a try, _should_ fix the wrong speed message and tell you set image state is not supported: https://github.com/thedjnK/AuTerm-Build/actions/runs/11969635739

**Comment by butok** [comment] 2024-11-22 09:56
> > > I'll add some more debug for that as the issue is not addressed after all. How long does it take to upload that file to your device, less than 1 second?
> > 
> > 
> > <1 second
> 
> You have the fastest device/upload using MCUmgr I've ever seen
> 
> Give this a try, _should_ fix the wrong speed message and tell you set image state is not supported: https://github.com/thedjnK/AuTerm-Build/actions/runs/11969635739

 - The wrong speed message has been fixed
 - No change for error message, still prints "Command not supported"

**Comment by thedjnK** [comment] 2024-11-22 14:19
Should check things before pushing, should be fixed here: https://github.com/thedjnK/AuTerm-Build/actions/runs/11974322055

**Comment by thedjnK** [comment] 2024-11-22 14:29
https://github.com/thedjnK/AuTerm-Build/actions/runs/11974437712 should fix it

**Comment by butok** [comment] 2024-11-22 14:37
> https://github.com/thedjnK/AuTerm-Build/actions/runs/11974437712 should fix it

Fixed. Thank you.

**Comment by thedjnK** [comment] 2024-11-24 16:05
Fixed in 0.35

**Closed by thedjnK** 2024-11-24 16:05 UTC
Labels: enhancement, area: MCUmgr plugin

**Comment by butok** [comment] 2024-11-28 11:52
Proposal for improvement:
Choose "No Action" by default.  So an user should intentionally set "Test" or "Confirmed".
